// Mix of old and new titles - should be re-generated at some point
export default new Map([
  ["{220} lattice spacing of silicon", true],
  ["Alpha particle mass energy equivalent", false],
  ["Alpha particle mass in u", false],
  ["Alpha particle mass", true],
  ["Alpha particle molar mass", true],
  ["Alpha particle relative atomic mass", false],
  ["Alpha particle-electron mass ratio", false],
  ["Alpha particle-proton mass ratio", false],
  ["Angstrom star", true],
  ["Atomic mass constant energy equivalent", false],
  ["Atomic mass constant", true],
  ["Atomic mass unit-electron volt relationship", false],
  ["Atomic mass unit-hartree relationship", false],
  ["Atomic mass unit-hertz relationship", false],
  ["Atomic mass unit-inverse meter relationship", false],
  ["Atomic mass unit-joule relationship", false],
  ["Atomic mass unit-kelvin relationship", false],
  ["Atomic mass unit-kilogram relationship", false],
  ["Atomic unit of 1st hyperpolarizability", false],
  ["Atomic unit of 2nd hyperpolarizability", false],
  ["Atomic unit of action", false],
  ["Atomic unit of charge density", false],
  ["Atomic unit of charge", false],
  ["Atomic unit of current", false],
  ["Atomic unit of electric dipole moment", false],
  ["Atomic unit of electric field gradient", false],
  ["Atomic unit of electric field", false],
  ["Atomic unit of electric polarizability", false],
  ["Atomic unit of electric potential", false],
  ["Atomic unit of electric quadrupole moment", false],
  ["Atomic unit of energy", false],
  ["Atomic unit of force", false],
  ["Atomic unit of length", false],
  ["Atomic unit of magnetic dipole moment", false],
  ["Atomic unit of magnetic flux density", false],
  ["Atomic unit of magnetizability", false],
  ["Atomic unit of mass", false],
  ["Atomic unit of momentum", false],
  ["Atomic unit of permittivity", false],
  ["Atomic unit of time", false],
  ["Atomic unit of velocity", false],
  ["Avogadro constant", true],
  ["Bohr magneton in Hz/T", false],
  ["Bohr magneton in inverse meter per tesla", false],
  ["Bohr magneton in inverse meters per tesla", false],
  ["Bohr magneton in K/T", false],
  ["Bohr magneton", true],
  ["Bohr radius", true],
  ["Boltzmann constant in Hz/K", false],
  ["Boltzmann constant in inverse meter per kelvin", false],
  ["Boltzmann constant in inverse meters per kelvin", false],
  ["Boltzmann constant", true],
  ["Characteristic impedance of vacuum", true],
  ["Classical electron radius", true],
  ["Compton wavelength over 2 pi", false],
  ["Compton wavelength", true],
  ["Conductance quantum", true],
  ["Conventional value of ampere-90", true],
  ["Conventional value of coulomb-90", true],
  ["Conventional value of farad-90", true],
  ["Conventional value of henry-90", true],
  ["Conventional value of Josephson constant", true],
  ["Conventional value of ohm-90", true],
  ["Conventional value of volt-90", true],
  ["Conventional value of von Klitzing constant", true],
  ["Conventional value of watt-90", true],
  ["Copper x unit", false],
  ["Cu x unit", false],
  ["Deuteron g factor", true],
  ["Deuteron magnetic moment to Bohr magneton ratio", false],
  ["Deuteron magnetic moment to nuclear magneton ratio", false],
  ["Deuteron magnetic moment", true],
  ["Deuteron mass energy equivalent", false],
  ["Deuteron mass in u", false],
  ["Deuteron mass", true],
  ["Deuteron molar mass", true],
  ["Deuteron relative atomic mass", false],
  ["Deuteron rms charge radius", true],
  ["Deuteron-electron magnetic moment ratio", false],
  ["Deuteron-electron mass ratio", false],
  ["Deuteron-neutron magnetic moment ratio", false],
  ["Deuteron-proton magnetic moment ratio", false],
  ["Deuteron-proton mass ratio", false],
  ["Electric constant", true],
  ["Electron charge to mass quotient", false],
  ["Electron g factor", true],
  ["Electron gyromagnetic ratio in MHz/T", false],
  ["Electron gyromagnetic ratio over 2 pi", false],
  ["Electron gyromagnetic ratio", false],
  ["Electron magnetic moment anomaly", true],
  ["Electron magnetic moment to Bohr magneton ratio", false],
  ["Electron magnetic moment to nuclear magneton ratio", false],
  ["Electron magnetic moment", true],
  ["Electron mass energy equivalent", false],
  ["Electron mass in u", false],
  ["Electron mass", true],
  ["Electron molar mass", true],
  ["Electron relative atomic mass", false],
  ["Electron to alpha particle mass ratio", false],
  ["Electron to shielded helion magnetic moment ratio", false],
  ["Electron to shielded proton magnetic moment ratio", false],
  ["Electron volt-atomic mass unit relationship", false],
  ["Electron volt-hartree relationship", false],
  ["Electron volt-hertz relationship", false],
  ["Electron volt-inverse meter relationship", false],
  ["Electron volt-joule relationship", false],
  ["Electron volt-kelvin relationship", false],
  ["Electron volt-kilogram relationship", false],
  ["Electron volt", true],
  ["Electron-deuteron magnetic moment ratio", false],
  ["Electron-deuteron mass ratio", false],
  ["Electron-helion mass ratio", false],
  ["Electron-muon magnetic moment ratio", false],
  ["Electron-muon mass ratio", false],
  ["Electron-neutron magnetic moment ratio", false],
  ["Electron-neutron mass ratio", false],
  ["Electron-proton magnetic moment ratio", false],
  ["Electron-proton mass ratio", false],
  ["Electron-tau mass ratio", false],
  ["Electron-triton mass ratio", false],
  ["Elementary charge over h-bar", false],
  ["Elementary charge over h", false],
  ["Elementary charge", true],
  ["Faraday constant for conventional electric current", true],
  ["Faraday constant", true],
  ["Fermi coupling constant", false],
  ["Fine-structure constant", true],
  ["First radiation constant for spectral radiance", true],
  ["First radiation constant", true],
  ["Hartree energy", true],
  ["Hartree-atomic mass unit relationship", false],
  ["Hartree-electron volt relationship", false],
  ["Hartree-hertz relationship", false],
  ["Hartree-inverse meter relationship", false],
  ["Hartree-joule relationship", false],
  ["Hartree-kelvin relationship", false],
  ["Hartree-kilogram relationship", false],
  ["Helion g factor", true],
  ["Helion magnetic moment to Bohr magneton ratio", false],
  ["Helion magnetic moment to nuclear magneton ratio", false],
  ["Helion magnetic moment", true],
  ["Helion mass energy equivalent", false],
  ["Helion mass in u", false],
  ["Helion mass", true],
  ["Helion molar mass", true],
  ["Helion relative atomic mass", false],
  ["Helion shielding shift", false],
  ["Helion-electron mass ratio", false],
  ["Helion-proton mass ratio", false],
  ["Hertz-atomic mass unit relationship", false],
  ["Hertz-electron volt relationship", false],
  ["Hertz-hartree relationship", false],
  ["Hertz-inverse meter relationship", false],
  ["Hertz-joule relationship", false],
  ["Hertz-kelvin relationship", false],
  ["Hertz-kilogram relationship", false],
  ["Hyperfine transition frequency of Cs-133", false],
  ["Inverse fine-structure constant", true],
  ["Inverse meter-atomic mass unit relationship", false],
  ["Inverse meter-electron volt relationship", false],
  ["Inverse meter-hartree relationship", false],
  ["Inverse meter-hertz relationship", false],
  ["Inverse meter-joule relationship", false],
  ["Inverse meter-kelvin relationship", false],
  ["Inverse meter-kilogram relationship", false],
  ["Inverse of conductance quantum", true],
  ["Josephson constant", true],
  ["Joule-atomic mass unit relationship", false],
  ["Joule-electron volt relationship", false],
  ["Joule-hartree relationship", false],
  ["Joule-hertz relationship", false],
  ["Joule-inverse meter relationship", false],
  ["Joule-kelvin relationship", false],
  ["Joule-kilogram relationship", false],
  ["Kelvin-atomic mass unit relationship", false],
  ["Kelvin-electron volt relationship", false],
  ["Kelvin-hartree relationship", false],
  ["Kelvin-hertz relationship", false],
  ["Kelvin-inverse meter relationship", false],
  ["Kelvin-joule relationship", false],
  ["Kelvin-kilogram relationship", false],
  ["Kilogram-atomic mass unit relationship", false],
  ["Kilogram-electron volt relationship", false],
  ["Kilogram-hartree relationship", false],
  ["Kilogram-hertz relationship", false],
  ["Kilogram-inverse meter relationship", false],
  ["Kilogram-joule relationship", false],
  ["Kilogram-kelvin relationship", false],
  ["Lattice parameter of silicon", true],
  ["Lattice spacing of ideal Si (220)", true],
  ["Loschmidt constant (273.15 K, 100 kPa)", true],
  ["Loschmidt constant (273.15 K, 101.325 kPa)", true],
  ["Luminous efficacy", false],
  ["Magnetic constant", true],
  ["Magnetic flux quantum", true],
  ["Mo x unit", false],
  ["Molar gas constant", true],
  ["Molar mass constant", true],
  ["Molar mass of carbon-12", true],
  ["Molar Planck constant times c", false],
  ["Molar Planck constant", true],
  ["Molar volume of ideal gas (273.15 K, 100 kPa)", true],
  ["Molar volume of ideal gas (273.15 K, 101.325 kPa)", true],
  ["Molar volume of silicon", true],
  ["Molybdenum x unit", false],
  ["Muon Compton wavelength over 2 pi", false],
  ["Muon Compton wavelength", true],
  ["Muon g factor", true],
  ["Muon magnetic moment anomaly", true],
  ["Muon magnetic moment to Bohr magneton ratio", false],
  ["Muon magnetic moment to nuclear magneton ratio", false],
  ["Muon magnetic moment", true],
  ["Muon mass energy equivalent", false],
  ["Muon mass in u", false],
  ["Muon mass", true],
  ["Muon molar mass", true],
  ["Muon-electron mass ratio", false],
  ["Muon-neutron mass ratio", false],
  ["Muon-proton magnetic moment ratio", false],
  ["Muon-proton mass ratio", false],
  ["Muon-tau mass ratio", false],
  ["Natural unit of action", false],
  ["Natural unit of energy", false],
  ["Natural unit of length", false],
  ["Natural unit of mass", false],
  ["Natural unit of momentum", false],
  ["Natural unit of time", false],
  ["Natural unit of velocity", false],
  ["Neutron Compton wavelength over 2 pi", false],
  ["Neutron Compton wavelength", true],
  ["Neutron g factor", true],
  ["Neutron gyromagnetic ratio in MHz/T", false],
  ["Neutron gyromagnetic ratio over 2 pi", false],
  ["Neutron gyromagnetic ratio", false],
  ["Neutron magnetic moment to Bohr magneton ratio", false],
  ["Neutron magnetic moment to nuclear magneton ratio", false],
  ["Neutron magnetic moment", true],
  ["Neutron mass energy equivalent", false],
  ["Neutron mass in u", false],
  ["Neutron mass", true],
  ["Neutron molar mass", true],
  ["Neutron relative atomic mass", false],
  ["Neutron to shielded proton magnetic moment ratio", false],
  ["Neutron-electron magnetic moment ratio", false],
  ["Neutron-electron mass ratio", false],
  ["Neutron-muon mass ratio", false],
  ["Neutron-proton magnetic moment ratio", false],
  ["Neutron-proton mass difference energy equivalent", false],
  ["Neutron-proton mass difference in u", false],
  ["Neutron-proton mass difference", false],
  ["Neutron-proton mass ratio", false],
  ["Neutron-tau mass ratio", false],
  ["Newtonian constant of gravitation over h-bar c", false],
  ["Newtonian constant of gravitation", true],
  ["Nuclear magneton in inverse meter per tesla", false],
  ["Nuclear magneton in inverse meters per tesla", false],
  ["Nuclear magneton in K/T", false],
  ["Nuclear magneton in MHz/T", false],
  ["Nuclear magneton", true],
  ["Planck constant over 2 pi", true],
  ["Planck constant", true],
  ["Planck length", true],
  ["Planck mass", true],
  ["Planck temperature", true],
  ["Planck time", true],
  ["Proton charge to mass quotient", false],
  ["Proton Compton wavelength over 2 pi", false],
  ["Proton Compton wavelength", true],
  ["Proton g factor", true],
  ["Proton gyromagnetic ratio in MHz/T", false],
  ["Proton gyromagnetic ratio over 2 pi", false],
  ["Proton gyromagnetic ratio", false],
  ["Proton magnetic moment to Bohr magneton ratio", false],
  ["Proton magnetic moment to nuclear magneton ratio", false],
  ["Proton magnetic moment", true],
  ["Proton magnetic shielding correction", true],
  ["Proton mass energy equivalent", false],
  ["Proton mass in u", false],
  ["Proton mass", true],
  ["Proton molar mass", true],
  ["Proton relative atomic mass", false],
  ["Proton rms charge radius", true],
  ["Proton-electron mass ratio", false],
  ["Proton-muon mass ratio", false],
  ["Proton-neutron magnetic moment ratio", false],
  ["Proton-neutron mass ratio", false],
  ["Proton-tau mass ratio", false],
  ["Quantum of circulation times 2", false],
  ["Quantum of circulation", false],
  ["Reduced Compton wavelength", false],
  ["Reduced muon Compton wavelength", false],
  ["Reduced neutron Compton wavelength", false],
  ["Reduced Planck constant", true],
  ["Reduced proton Compton wavelength", false],
  ["Reduced tau Compton wavelength", false],
  ["Rydberg constant times c in Hz", false],
  ["Rydberg constant times hc in J", false],
  ["Rydberg constant", true],
  ["Sackur-Tetrode constant (1 K, 100 kPa)", false],
  ["Sackur-Tetrode constant (1 K, 101.325 kPa)", false],
  ["Second radiation constant", true],
  ["Shielded helion gyromagnetic ratio in MHz/T", false],
  ["Shielded helion gyromagnetic ratio over 2 pi", false],
  ["Shielded helion gyromagnetic ratio", false],
  ["Shielded helion magnetic moment to Bohr magneton ratio", false],
  ["Shielded helion magnetic moment to nuclear magneton ratio", false],
  ["Shielded helion magnetic moment", true],
  ["Shielded helion to proton magnetic moment ratio", false],
  ["Shielded helion to shielded proton magnetic moment ratio", false],
  ["Shielded proton gyromagnetic ratio in MHz/T", false],
  ["Shielded proton gyromagnetic ratio over 2 pi", false],
  ["Shielded proton gyromagnetic ratio", false],
  ["Shielded proton magnetic moment to Bohr magneton ratio", false],
  ["Shielded proton magnetic moment to nuclear magneton ratio", false],
  ["Shielded proton magnetic moment", true],
  ["Shielding difference of d and p in HD", false],
  ["Shielding difference of t and p in HT", false],
  ["Speed of light in vacuum", true],
  ["Standard acceleration of gravity", true],
  ["Standard atmosphere", true],
  ["Standard-state pressure", true],
  ["Stefan-Boltzmann constant", true],
  ["Tau Compton wavelength over 2 pi", false],
  ["Tau Compton wavelength", true],
  ["Tau energy equivalent", false],
  ["Tau mass energy equivalent", false],
  ["Tau mass in u", false],
  ["Tau mass", true],
  ["Tau molar mass", true],
  ["Tau-electron mass ratio", false],
  ["Tau-muon mass ratio", false],
  ["Tau-neutron mass ratio", false],
  ["Tau-proton mass ratio", false],
  ["Thomson cross section", true],
  ["Triton g factor", true],
  ["Triton magnetic moment to Bohr magneton ratio", false],
  ["Triton magnetic moment to nuclear magneton ratio", false],
  ["Triton magnetic moment", true],
  ["Triton mass energy equivalent", false],
  ["Triton mass in u", false],
  ["Triton mass", true],
  ["Triton molar mass", true],
  ["Triton relative atomic mass", false],
  ["Triton to proton magnetic moment ratio", false],
  ["Triton-electron mass ratio", false],
  ["Triton-proton mass ratio", false],
  ["Unified atomic mass unit", true],
  ["Vacuum electric permittivity", false],
  ["Vacuum magnetic permeability", false],
  ["Von Klitzing constant", true],
  ["W to Z mass ratio", false],
  ["Weak mixing angle", false],
  ["Wien frequency displacement law constant", true],
  ["Wien wavelength displacement law constant", true],
]);
